name: test
title: null
remote_theme: jekyll/minima
minima:
  skin: dark
  date_format: "%b %-d, %Y"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
